language: node_js

node_js:
  - "8"

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
